spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://39.98.148.78:3306/c2m?serverTimezone=GMT%2B8&useSSL=false
spring.datasource.username=root
spring.datasource.password=Bora!@#123
entity.mysql.path=com.zj.customField.test.entity
authorname.mysql.path=zhangjing
